# ML & Data Analysis of Radioactive Decay

In [1]:
# importing necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

import warnings
warnings.filterwarnings('ignore')

In [3]:
# loading the dataset

df = pd.read_csv("quantum_radioactive_decay_dataset.csv")

print("Dataset Loaded Successfully!")
print(df)

Dataset Loaded Successfully!
       sample_id  initial_atoms  decay_constant       time  remaining_atoms  \
0              1           1360        0.268150   0.100531        1341.1573
1              1           1360        0.268150   1.201928         969.6685
2              1           1360        0.268150   1.779794         866.5236
3              1           1360        0.268150   2.845105         670.6214
4              1           1360        0.268150   3.297696         538.3445
...          ...            ...             ...        ...              ...
24995       1000           3268        0.131594  14.060937         509.5924
24996       1000           3268        0.131594  14.644545              NaN
24997       1000           3268        0.131594  15.761447         409.2425
24998       1000           3268             NaN  17.107488         372.8704
24999       1000           3268        0.131594  18.476678         293.9599

       decayed_atoms  probability_of_decay  half_life  noise_level  \
0            18.8427              0.026597   2.584921      41.7517
1           390.3315              0.275517   2.584921      24.2653
2           493.4764              0.379514   2.584921      19.6720
3           689.3786              0.533695   2.584921      20.0019
4           821.6555              0.586988   2.584921      14.5708
...              ...                   ...        ...          ...
24995      2758.4076              0.842815   5.267329      18.0631
24996            NaN              0.854435   5.267329      24.5295
24997      2858.7575              0.874331   5.267329      10.4449
24998      2895.1296              0.894731   5.267329      19.3661
24999      2974.0401              0.912088   5.267329       9.4596

      experiment_group
0                    E
1                    E
2                    E
3                    E
4                    E
...                ...
24995                A
24996                A
24997                A
24998                A
24999                A

[25000 rows x 10 columns]

In [4]:
# exploring the dataset

print("Shape of Dataset:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

Shape of Dataset:
(25000, 10)

Columns:
Index(['sample_id', 'initial_atoms', 'decay_constant', 'time',
       'remaining_atoms', 'decayed_atoms', 'probability_of_decay', 'half_life',
       'noise_level', 'experiment_group'],
      dtype='str')

First 5 Rows:

,sample_id,initial_atoms,decay_constant,time,remaining_atoms,decayed_atoms,probability_of_decay,half_life,noise_level,experiment_group
0,1,1360,0.26815,0.100531,1341.1573,18.8427,0.026597,2.584921,41.7517,E
1,1,1360,0.26815,1.201928,969.6685,390.3315,0.275517,2.584921,24.2653,E
2,1,1360,0.26815,1.779794,866.5236,493.4764,0.379514,2.584921,19.6720,E
3,1,1360,0.26815,2.845105,670.6214,689.3786,0.533695,2.584921,20.0019,E
4,1,1360,0.26815,3.297696,538.3445,821.6555,0.586988,2.584921,14.5708,E

Last 5 Rows:

,sample_id,initial_atoms,decay_constant,time,remaining_atoms,decayed_atoms,probability_of_decay,half_life,noise_level,experiment_group
24995,1000,3268,0.131594,14.060937,509.5924,2758.4076,0.842815,5.267329,18.0631,A
24996,1000,3268,0.131594,14.644545,NaN,NaN,0.854435,5.267329,24.5295,A
24997,1000,3268,0.131594,15.761447,409.2425,2858.7575,0.874331,5.267329,10.4449,A
24998,1000,3268,NaN,17.107488,372.8704,2895.1296,0.894731,5.267329,19.3661,A
24999,1000,3268,0.131594,18.476678,293.9599,2974.0401,0.912088,5.267329,9.4596,A

In [ ]:
# Basic information about the dataset
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   sample_id             25000 non-null  int64
 1   initial_atoms         25000 non-null  int64
 2   decay_constant        24420 non-null  float64
 3   time                  24427 non-null  float64
 4   remaining_atoms       24298 non-null  float64
 5   decayed_atoms         24298 non-null  float64
 6   probability_of_decay  25000 non-null  float64
 7   half_life             25000 non-null  float64
 8   noise_level           25000 non-null  float64
 9   experiment_group      25000 non-null  str
dtypes: float64(7), int64(2), str(1)
memory usage: 1.9 MB
None

In [6]:
# checking for missing values


missing = df.isnull().sum()

print("Missing Values:")
print(missing)

# Percentage missing
missing_percent = (missing / len(df)) * 100

print("\nMissing Percentage:")
print(missing_percent)

Missing Values:
sample_id                 0
initial_atoms             0
decay_constant          580
time                    573
remaining_atoms         702
decayed_atoms           702
probability_of_decay      0
half_life                 0
noise_level               0
experiment_group          0
dtype: int64

Missing Percentage:
sample_id               0.000
initial_atoms           0.000
decay_constant          2.320
time                    2.292
remaining_atoms         2.808
decayed_atoms           2.808
probability_of_decay    0.000
half_life               0.000
noise_level             0.000
experiment_group        0.000
dtype: float64